platform :ios, '9.0'

target 'Todoey' do
  use_frameworks!

  pod 'RealmSwift'
  pod 'SwipeCellKit'
  pod 'ChameleonFramework/Swift' #, :git => 'https://github.com/AhmedFathi680/Chameleon.git', :branch => 'swift5'
end
